name: Cart CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo npm test
  docker:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: docker login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 389841108590.dkr.ecr.us-east-1.amazonaws.com
      - run: docker build -t 389841108590.dkr.ecr.us-east-1.amazonaws.com/cart .
        name: docker build
      - run: docker push 389841108590.dkr.ecr.us-east-1.amazonaws.com/cart
        name: docker build
  dev-deploy:
    runs-on: self-hosted
    environment: dev
    needs: docker
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: helm deploy app
        run: helm upgrade -i cart . -f dev-values/cart.yml

  qa-deploy:
    runs-on: self-hosted
    needs: dev-deploy
    environment: qa
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: get kubectl config
        run: echo aws eks update-kubeconfig --name qa
      - name: helm deploy app
        run: echo helm upgrade -i cart . -f dev-values/cart.yml

  uat-deploy:
    runs-on: self-hosted
    needs: qa-deploy
    environment: uat
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: get kubectl config
        run: echo aws eks update-kubeconfig --name uat
      - name: helm deploy app
        run: echo helm upgrade -i cart . -f dev-values/cart.yml

  prod-deploy:
    runs-on: self-hosted
    needs: uat-deploy
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: echo get kubectl config
        run: aws eks update-kubeconfig --name prod
      - name: helm deploy app
        run: echo helm upgrade -i cart . -f dev-values/cart.yml